spring:
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    password: 171198nik
    username: postgres
server:
  port: 8080
  servlet:
    context-path: /restaurant